### ISSUE TITLE
Working with url crate

### ISSUE THREAD

**Issue by xoac** [NotBad4U/query_params#1]
Hi,
It's just idea. 

There is a quite good [url](https://github.com/servo/rust-url) lib that could match your library. 

There is a [set_query](https://docs.rs/url/1.6.0/url/struct.Url.html#method.set_query) method that near match your `to_query_params()`.

Your generate `?sth=2` `url` accept `Some("sth=2")` (without `?`). I think it would be nice to make your solution merged. Serialize structures with `derive` is nice future. 

Problem occurs when your struct contains only `Option` and you can generate empty str. 
```rust
let generated_query =  structure.to_query_params();
if generated_query.len() > 0 {      
      url.set_query(Some(&generated_query.as_str()[1..]));     
  }
```
I will link to this issue from url. Maybe sb will be interested and find a nice solution.

**Comment by NotBad4U** [comment]
Hi, srry for the delay I was quite busy this weeks.
So I don't know if it's a great idea to refactor this behavior: remove the `?` and return an `Option`, only to work with the crate `url`.

I see 2 options: 
- Make a new method that return only the query params without the `?` (or use a flag) and encapsulate the result in an app with `set_queries(Some(structure.to_query_params()))`.
- Make a PR to `url`lib to set the behavior of `set_qery` not `?`  sensitive.

**Comment by xoac** [comment]
@NotBad4U Thanks for response. 

Second option is wrong solution. https://stackoverflow.com/questions/2924160/is-it-valid-to-have-more-than-one-question-mark-in-a-url
This will make `set_query` working improper with `Some("??IWantThisQuestionMarkInMyQuery")`
